```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = F)
```

```{r load.packages, include = FALSE}
library(papaja)
library(tidyverse)

rm(list = ls())

load("data/base data.rdata")
```

## SUBS


```{r SUBS_Funcs}
library(parallel)
library(fpc)
library(cluster)
library(tidyverse)


run_clusters <- function(K, distance) {

  # # Calculate the number of cores
  # no_cores <- min(K, detectCores() - 7)
  # 
  # # Initiate cluster
  # cl <- makeCluster(no_cores)
  # 
  # clusters <- parLapply(cl, 1:K, function(x, y) kmeans(x = y, centers = x), distance)
  # 
  # stopCluster(cl)
  # 
  # # clusters <- bind_cols(clusters)
  # #
  # # names(classign) <- paste("k", 1:K, sep = "")
  
  clusters <- list()
  
  for(k in 1:K) {
    clusters <- append(clusters, list(genClusters(distance = distance, k = k)))
  }

  return(clusters)
}

genClusters <- function(distance, k, iterations = 10) {
  clusters <- list()
  withins <- NULL
  # seeds <- NULL
  
  for(i in 1:iterations){
    seed <- round(runif(1, 0, 1) * 10^6,0)
    set.seed(seed)
    
    clust <- kmeans(x = distance, centers = k)
    clust <- append(clust, list(seed = seed))
    withins <- c(withins, clust$tot.withinss)
    clusters <- append(clusters, list(clust))
  }
  
  return(clusters[[which(withins == min(withins))[1]]])
  
}

get_CH <- function(K, distance, clusters) {
  ch <- list()
  
  for(k in 2:K) {
    ch1 <- (clusters[[k]]$betweenss / (k - 1)) / (clusters[[k]]$tot.withinss / (length(clusters[[k]]$cluster- k)))
    ch2 <- cluster.stats(distance, clusters[[k]]$cluster,
                                silhouette = F, G2 = FALSE, G3 = FALSE,
                                wgap=F, sepindex=F, sepprob=0.1,
                                sepwithnoise=F)
    ch_d <- ch2$ch
    
    ch = append(ch , list(k = k, 
                     ch = ch1,
                     ch_d = ch_d))
  }
  
  chPlot <- unlist(ch) %>%
  matrix(3, (K-1)) %>%
  t() %>%
  as.data.frame %>%
  mutate(dif = abs(V2 - V3))
  
  names(chPlot) <- c("k", "ch1", "ch2", "dif")

  
  return(chPlot)
}

```

### Number of Clusters

### Subs-Full


```{r SUBS_FULL, eval = F}
# K <- 20
# 
# distance <- df[, subs_f_vars] %>%
#   mutate(MEDINC = log(MEDINC),
#          n = log(n)) %>%
#   # sample_n(500) %>%
#   daisy(metric = "gower")
# 
# 
# clust_time <- system.time(
#   clusters <- run_clusters(K, distance)
# )
# 
# ch_time <- system.time(
#   chPlot <- get_CH(K, distance, clusters)
# )
# 
# # undebug(get_CH)
# 
# save(clusters, chPlot, clust_time, ch_time, K, distance, file =  "Paper Data/clusters-full-logs.rdata")
```

```{r SUBS_FULL_CH}
# load("clusters-full.rdata")
load("Paper Data/clusters-full-logs.rdata")


chPlot %>%
  gather(key = method, value = value, ch1:dif) %>%
  ggplot(aes(x = k, y = value, color = method)) +
  geom_point() +
  geom_line() +
  theme_apa() +
  scale_x_discrete(limits = c(1:K))



```

```{r SUBS_FULL_SSB/SST}
cls <- bind_cols(lapply(clusters, function(x) data.frame(x$cluster)))
vrat <- unlist(lapply(clusters, function(x) x$betweenss / x$totss))

data.frame(k = 1:K, var = vrat, min80 = sum(vrat < .8) + .5) %>%
  ggplot(aes(x = k, y = var)) +
  geom_point() +
  ggtitle("Between cluster variance by number of strata") +
  labs(y = "Between Cluster Variance",
       x = "Number of Strata (k)") +
  geom_line() +
  geom_vline(aes(xintercept = min80), linetype = "dashed") +
  theme_apa() +
  scale_x_discrete(limits = c(1:K)) +
  scale_y_continuous(breaks = seq(0, 1, .1))

df$cluster_full_6 <- cls[,6]
df$cluster_full_10 <- cls[,10]
# dist_full <- distance

```

### Subs-OV


```{r SUBS_OV, eval = F}

# K <- 20
# 
# distance <- df[, subs_ov_vars] %>%
#   mutate(n = log(n)) %>%
#   daisy(metric = "gower")
# 
# 
# clust_time <- system.time(
#   clusters <- run_clusters(K, distance)
# )
# 
# ch_time <- system.time(
#   chPlot <- get_CH(K, distance, clusters)
# )
# 
# 
# save(clusters, chPlot, clust_time, ch_time, K, distance, file =  "Paper Data/clusters-OV-logs.rdata")

```

```{r SUBS_OV_CH}
# load("clusters-OV.rdata")
load("Paper Data/clusters-OV-logs.rdata")


chPlot %>%
  gather(key = method, value = value, ch1:dif) %>%
  ggplot(aes(x = k, y = value, color = method)) +
  geom_point() +
  geom_line()



```

```{r SUBS_OV_SSB/SST}
cls <- bind_cols(lapply(clusters, function(x) data.frame(x$cluster)))
vrat <- unlist(lapply(clusters, function(x) x$betweenss / x$totss))

data.frame(k = 1:K, var = vrat, min80 = sum(vrat < .8) + .5) %>%
  ggplot(aes(x = k, y = var)) +
  geom_point() +
  ggtitle("Between cluster variance by number of strata") +
  labs(y = "Between Cluster Variance",
       x = "Number of Strata (k)") +
  geom_line() +
  geom_vline(aes(xintercept = min80), linetype = "dashed") +
  theme_minimal() +
  scale_x_discrete(limits = c(1:K)) +
  scale_y_continuous(breaks = seq(0, 1, .1))

df$cluster_OV_6 <- cls[,6]
df$cluster_OV_10 <- cls[,10]

df.clusts <- df %>% 
  select(DSID, cluster_OV_6, cluster_full_6)

save(df.clusts, file = "Params/Clusters.rdata")
```

```{r}
orig <- df
df <- orig
```


```{r class_full}
df %>%
  select(cluster_full_6:cluster_OV_10) %>%
  rbind(rbind(mutate(., cluster_full_6 = 20),
              mutate(., cluster_full_10 = 20))) %>%
  group_by(cluster_full_6, cluster_full_10) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  # mutate(p = n/sum(n)) %>%
  spread(key = cluster_full_6, value = n)

```

```{r class_OV}
# df %>%
#   select(cluster_full_6:cluster_OV_10) %>%
#   rbind(rbind(mutate(., cluster_OV_6 = 20), 
#               mutate(., cluster_OV_10 = 20))) %>%
#   group_by(cluster_OV_6, cluster_OV_10) %>%
#   summarise(n = n()) %>%
#   ungroup() %>%
#   # mutate(p = n/sum(n)) %>%
#   spread(key = cluster_OV_6, value = n)

```

### 6 Clusters

```{r class_k6}
df %>%
  select(cluster_full_6:cluster_OV_10) %>%
  rbind(rbind(mutate(., cluster_full_6 = 20),
  mutate(., cluster_OV_6 = 20))) %>%
  group_by(cluster_full_6, cluster_OV_6) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  # mutate(p = n/sum(n)) %>%
  spread(key = cluster_full_6, value = n)

similar <- df %>%
  select(cluster_full_6:cluster_OV_10) %>%
  group_by(cluster_full_6, cluster_OV_6) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

similar

similar <- rbind(similar[c(1:5),1:2], c(cluster_full_6 = 4, cluster_OV_6 = 4)) %>% arrange(cluster_full_6)

df$cluster_OV_6 <- factor(df$cluster_OV_6)
df$cluster_full_6 <- factor(df$cluster_full_6)

levels(df$cluster_full_6) <- similar$cluster_OV_6
```



```{r}
df %>%
  select(urbanicity, pELA, pMath, cluster_full_6, cluster_OV_6) %>%
  gather(key = full_ov, value = cluster, cluster_full_6:cluster_OV_6) %>%
  ggplot(aes(x = pELA, y = pMath, color = as.factor(cluster))) +
  geom_point() +
  facet_grid(urbanicity ~ full_ov) +
  scale_color_brewer(type = "div")

```

```{r}
df %>%
  select(urbanicity, pELL, pED, cluster_full_6, cluster_OV_6) %>%
  gather(key = full_ov, value = cluster, cluster_full_6:cluster_OV_6) %>%
  ggplot(aes(x = pELL, y = pED, color = cluster)) +
  geom_point() +
  facet_grid(urbanicity ~ full_ov) +
  scale_color_brewer(type = "div")

```

### 10 Clusters

```{r class_k10}
df %>%
  select(cluster_full_10:cluster_OV_10) %>%
  rbind(rbind(mutate(., cluster_full_10 = 20), 
              mutate(., cluster_OV_10 = 20))) %>%
  group_by(cluster_full_10, cluster_OV_10) %>%
  summarise(n = n()) %>%
  ungroup() %>%
  # mutate(p = n/sum(n)) %>%
  spread(key = cluster_full_10, value = n)

similar <- df %>%
  select(cluster_full_6:cluster_OV_10) %>%
  group_by(cluster_full_10, cluster_OV_10) %>%
  summarise(n = n()) %>%
  arrange(desc(n))

similar <- similar[c(1:10),1:2]

df$cluster_OV_10 <- factor(df$cluster_OV_10)
df$cluster_full_10 <- factor(df$cluster_full_10)

levels(df$cluster_full_10) <- similar$cluster_OV_10

```

```{r}
df %>%
  select(urbanicity, pELA, pMath, cluster_full_10, cluster_OV_10) %>%
  gather(key = full_ov, value = cluster, cluster_full_10:cluster_OV_10) %>%
  ggplot(aes(x = pELA, y = pMath, color = as.factor(cluster))) +
  geom_point() +
  facet_grid(urbanicity ~ full_ov) +
  scale_color_brewer(type = "div")

```

```{r}
df %>%
  select(urbanicity, pELL, pED, cluster_full_10, cluster_OV_10) %>%
  gather(key = full_ov, value = cluster, cluster_full_10:cluster_OV_10) %>%
  ggplot(aes(x = pELL, y = pED, color = cluster)) +
  geom_point() +
  facet_grid(urbanicity ~ full_ov) +
  scale_color_brewer(type = "div")

```

