---
title             : "GenSamp: RESULTS"
shorttitle        : "RESULTS"

author:
  - name          : "Gleb Furman"
    affiliation   : "1"
    # corresponding : yes    # Define only one corresponding author
    # address       : "Postal address"
    # email         : "Gleb.Furman@gmail.com"
  - name          : "James E. Pustejovsky"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "University of Texas at Austin"
#   - id            : "2"
#     institution   : "Konstanz Business School"

# author_note: |
#   Add complete departmental affiliations for each author here. Each new line herein must be indented, like this line.

#   Enter author note here.

abstract: |
    <!-- In order for educational research to be informative to policy makers, studies must be designed to make robust estimates of causal effects at the population level. Large scale multi-site randomized trials (MRT) often rely on vague convenience sampling methodology when recruiting districts and schools, resulting in relatively homogeneous samples that may differ greatly from the intended population of interest. Retrospective methods that quantify and statistically adjust for those differences are promising but have limited effect when the sample differs greatly from the population. Designing sampling methods that focus on generalizability may be a more effective but costly solution, but limited methodological research has been performed to examine their effectiveness in the educational context. This paper examines one promising method, stratified balanced sampling (SBS), in the context of recruiting a representative sample of schools for a large scale MRT. Using simulations based on real data, we compare SBS to stratified and unstratified versions of convenience sampling and probability sampling. Several models for generating school participation and emulating convenience sampling are proposed. Results indicate that SBS and stratified random sampling (SRS) result in highly generalizable samples. These methods are extremely costly to implement, however, especially when the population average willingness to participate is low. Stratified convenience sampling (SCS) is a potential compromise. -->

# keywords          : "keywords"
# wordcount         : "X"

bibliography      : ["references.bib"]

figsintext        : yes
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : no
mask              : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, cache = F, warnings = F, cache = T)
```

```{r load.packages, include = FALSE}
library(papaja)
library(tidyverse)
library(kableExtra)

rm(list = ls())


load("Data/Simulation Data/Sim Data.Rdata")
load("Data/Cluster Analysis/Clusters k2-10.rdata")

# load(read_file("Data/Results/LastResults.txt"))
load("Data/Results/1001 Reps - K5.rdata")


rename_conditions <- function(orig.data) {
  orig.data %>%
    separate(col = sample_method, into = c("Clustering", "Sampling"), remove = F)
}

df.B.indicies <- df.B.indicies %>% rename_conditions()

df.recruitment.stats <- df.recruitment.stats %>% rename_conditions()

df.samp.counts <- df.samp.counts %>% rename_conditions()
  
df.samp.stats <- df.samp.stats %>% rename_conditions()


df.clusters <- df.clusters %>%
  transmute(DSID = DSID,
            strata = factor(K_05))

df <- left_join(df.sim, df.clusters)

### Calculate SMDs using IPSW
### Estimate variance explaiend by STRATA in covariates

savePlot <- F
```


```{r}
boxErrors <- function(x) {
  v <- c(min(x), mean(x) - sd(x), mean(x), mean(x) + sd(x), max(x))
  names(v) <- c("ymin", "lower", "middle", "upper", "ymax")
  v
}

```





# Methods Summary

## Clustering

```{r, results = "asis"}
library(tableone)

tab1 <- df %>%
  # droplevels() %>% 
  select(strata, covariates) %>%
  gather(key = var, value = val, -strata) %>%
  group_by(strata, var) %>%
  summarise(strat.mean = mean(val)) %>%
  left_join(df.pop.stats) %>%
  transmute(var = var,
            SMD = round((pop.mean - strat.mean) / pop.sd, 2))

# tab1 %>%
#   mutate(SMD = cell_spec(SMD, "latex", bold = abs(SMD) > .25)) %>%
#   kable() %>%
#   kable_styling()

tab1 %>%
  mutate(sig = ifelse(abs(SMD) > .25, "Sig", "Not Sig"),
         neg = SMD > 0) %>%
  ggplot(aes(x = strata, y = var, size = abs(SMD), color = neg, alpha = sig)) +
  geom_point(shape = "-") + 
  scale_size_continuous(range = c(10,30)) +
  theme(legend.position = "none") +
  scale_alpha_discrete(range = c(.5, 1))
  

df %>% 
  select(strata, covariates) %>%
  # select(strata, n, dSCH, ST.ratio) %>%
  mutate(n = log(n),
         dSCH = log(dSCH),
         ST.ratio = log(ST.ratio)) %>%
  gather(key = var, value = val, -strata) %>%
  ggplot(aes(x = strata, y = val)) + 
  geom_boxplot() + 
  facet_wrap(~ var, scales = "free_y") + 
  theme(legend.position = "none")

```

## Participation Generating Model

```{r}
df.coefs <- data.frame(Variables = names(DGM.Bs), vnames = names(DGM.Bs), log_odds = DGM.Bs, row.names = NULL) %>%
  arrange(Variables)

levels(df.coefs$Variables) <- c("Total District Schools", 
                                "% Black",
                                "% Hispanic",
                                "% White",
                                "Total Students",
                                "% ELL",
                                "% Female",
                                "% FRL", # Free Reduced Lunch
                                "Student/Teacher Ratio",
                                "Suburban",
                                "Schoolwide Title I",
                                "Town/Rural",
                                "Urban")

df.coefs %>%
  kable() %>%
  kable_styling()
```


```{r}
dist_plots <- df %>%
  select(covariates) %>%
  select_if(is.numeric) %>%
  mutate(n = log(n),
         ST.ratio = log(ST.ratio),
         dSCH = log(dSCH)) %>%
  gather(key = vnames, value = val) %>%
  left_join(df.coefs)


save(df, df.coefs, intercepts, chPlot, cluster.vratio, file = "Data/Paper/Paper Data.rdata")
```

```{r}


data.frame(Intercept = intercepts, RR = names(intercepts), row.names = NULL) %>%
  ggplot(aes(x = RR, y = Intercept, group = 1)) +
  geom_point() +
  geom_line() +
  theme_apa() +
  labs(title = "Intercept values")
```


```{r, fig.cap = "Distributions of Participation Propensity Scores"}
df.PS %>% 
  ggplot(aes(x = PS)) + 
  geom_histogram() + 
  facet_wrap(~RR, scales = "free") +
  theme_apa()


left_join(df.PS, df.clusters) %>%
  ggplot(aes(x = PS, color = strata, group = strata)) +
  geom_density() +
  facet_wrap(~RR, scales = "free_y")

left_join(df.PS, df.clusters) %>%
  ggplot(aes(x = strata, y = PS, color = strata)) +
  geom_boxplot() +
  facet_wrap(~RR, scales = "free_y") + 
  theme(legend.position = "none")

```


## B Index

```{r, fig.cap = "Averge B-Index"}

avg_Bindex <- df.B.indicies %>%
  group_by(sample_method, RR, Clustering, Sampling) %>%
  summarise(M = mean(Bs, na.rm = T),
            SD = sd(Bs, na.rm = T)) %>%
  mutate(LL = M - SD,
         UL = M + SD)

avg_Bindex %>%
  ggplot(aes(x = RR, y = M, color = Sampling, linetype = Clustering, group = sample_method)) +
  geom_line() +
  labs(y = "Mean B-index",
       x = "Population Participation Rate") +
  theme_apa() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


if(savePlot) ggsave(paste("Figs/", file_date, "/Paper B-Index.jpg", sep = ""), dpi = 1000, width = 7, height = 4)

# df.B.indicies %>%
#   group_by(sample_method, RR, Clustering, Sampling) %>%
#   summarise(NA.Count = sum(is.na(Bs))) %>%
#   spread(key = RR, value = NA.Count) 


```



## Standardized mean differences

```{r, fig.cap = "Average SMDs", fig.height = 7}
df.samp.stats <- df.samp.stats %>%
  left_join(df.pop.stats) %>%
  mutate(smd = (samp.mean - pop.mean) / pop.sd)


sSMDplot <- df.samp.stats %>%
  group_by(sample_method, RR, var, Sampling, Clustering, K) %>%
  summarise(mSMD = mean(abs(smd)),
            mSMD.sd = sd(abs(smd)))



sSMDplot %>%
  ggplot(aes(x = RR, y = mSMD, color = Sampling, linetype = Clustering, group = sample_method)) +
  # geom_point() +
  geom_line() +
  geom_hline(yintercept = 0) +
  geom_hline(yintercept = .25, linetype = "dashed") +
  facet_wrap( ~ var, scales = "free_y", ncol  = 3) +
  theme_apa(box = F) +
  labs(y = "Mean SMD",
       x = "Population Participation Rate") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

if(savePlot)  ggsave(paste("Figs/", file_date, "/All SMDs.jpg", sep = ""), dpi = 1000, width = 7, height = 5)

```



## Sampling Difficulty

```{r}
samplot <- df.recruitment.stats %>%
  group_by(sample_method, RR, measure, Sampling, Clustering, K) %>%
  summarise(value = mean(value))


```


```{r, fig.cap = "Recruitment Counts"}
samplot %>%
  ggplot(aes(x = RR, y = value, group = sample_method, color = Sampling, linetype = Clustering)) +
  geom_point() +
  geom_line() +
  facet_wrap( ~ measure, scales = "free_y") +
  expand_limits(y = 0) +
  theme_apa(box = T) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))




```





```{r, fig.cap = "Schools Contacted"}
samplot %>%
  filter(measure == "sch.contacted") %>%
  ggplot(aes(x = RR, y = value, group = sample_method, color = Sampling, linetype = Clustering)) +
  geom_point() +
  geom_line() +
  expand_limits(y = 0) +
  theme_apa(box = T) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

if(savePlot)  ggsave(paste("Figs/", file_date, "/Units Contacted.jpg", sep = ""), dpi = 1000, width = 7, height = 5)

```

```{r, fig.cap = "Sampling response rates"}
samplot %>%
  filter(measure == "sch.response.rate") %>%
  ggplot(aes(x = RR, y = value, group = sample_method, color = Sampling, linetype = Clustering)) +
  geom_point() +
  geom_line() +
  expand_limits(y = 0) +
  theme_apa(box = T) +
  theme(legend.position = "bottom",
        panel.spacing = unit(2, "lines"),
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Generating Repsonse Rate", y = "Actual Response Rate") 

```




```{r}

df.counts <- df.samp.counts %>%
  group_by_all() %>%
  count(name = "count") %>%
  ungroup() %>%
  mutate(perc = count/1001) %>%
  arrange(-perc) %>%
  left_join(df.sim) %>%
  group_by(sample_method, K, RR) %>%
  mutate(w = count / sum(count))

df.counts.pop <- df.PS %>%
  left_join(df.clusters) %>%
  left_join(df.sim)


```

```{r}
df.counts %>%
  ggplot() +
  geom_density(aes(x = PS, fill = sample_method, weight = w), alpha = .1) +
  geom_density(data = df.counts.pop,
               aes(x = PS)) +
  facet_grid(RR ~ Sampling, scales = "free")


```

```{r}
df.counts %>%
  ggplot() +
  geom_density(aes(x = ethHisp, fill = sample_method, weight = w), alpha = .1) +
  geom_density(data = df.counts.pop,
               aes(x = ethHisp)) +
  facet_grid(RR ~ Sampling, scales = "free")

```

```{r}
library(ICC)

df.ICCs <- df %>%
  gather(key = vnames, value = value, covariates) %>%
  group_by(vnames) %>%
  summarise(ICC = ICCbare(strata, value))

df.coefs %>%
  left_join(df.ICCs) %>%
  arrange(ICC)
```