---
title: "Untitled"
output: html_document
---

# Stratification



We demonstrate stratification within the context of selecting schools for a large-scale MRT, where the goal is to select a sample that is representative of a population with respect to a set of covariates related to treatment heterogeneity and site participation. When used for survey sampling or blocking in experimental studies, strata may be defined based on one or two covariates that lend themselves to categorization [@lohrSamplingDesignAnalysis2019]. In contrast, our purpose here is to reduce bias in the estimate by achieving balance on potential moderators---a task that requires a larger number of covariates of varying complexity. Traditional stratification at this scale would result in too many strata and an overly complicated recruitment process. Cluster analysis provides a way to define a tractable, smaller number of strata. 

We begin by explaining the data which will serve as the sampling frame and the covariates used in the cluster analysis process. We then implement k-medoids clustering to divide the population into heterogeneous strata comprised of homogeneous sites, generally following recommendations put forth by @tiptonStratifiedSamplingUsing2013. K-medoids clustering assigns sites to strata such that similarity within each stratum is maximized, where similarity is defined by a distance metric. We choose the number of strata to be generated by considering empirical criteria as well as subjective appraisals of what is feasible to implement. After arriving at a final clustering of schools, we illustrate how the strata explain variation in the underlying clusters. 

